DROP DATABASE IF EXISTS retodario;
CREATE DATABASE retodario;
USE retodario;

CREATE TABLE libros(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	nombre VARCHAR(128) NOT NULL,
	ISBN VARCHAR(13) NOT NULL,
	release_year INT(4),
	idioma VARCHAR(25)
);

CREATE TABLE autores(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	nombre VARCHAR(128) NOT NULL,
	pais_origen VARCHAR(128) NOT NULL,
	
);

CREATE TABLE categorias(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	nombre VARCHAR(128) NOT NULL
);

CREATE TABLE clientes(
	i

);